const SVG_OPTIMIZED_COMMENT_CONTENT = '@autogenerated optimization completed by @naverpay/optimize-svg-components'
const SVG_OPTIMIZE_COMPLETED_COMMENT = `/* ${SVG_OPTIMIZED_COMMENT_CONTENT} */`
const PROPS_IDENTIFIER_NAME = 'props'
const FIRST_RANGE = [0, 0]

module.exports = {
    PROPS_IDENTIFIER_NAME,
    SVG_OPTIMIZED_COMMENT_CONTENT,
    SVG_OPTIMIZE_COMPLETED_COMMENT,
    FIRST_RANGE,
}
