export const SVG_OPTIMIZED_COMMENT_CONTENT =
    '@autogenerated optimization completed by @naverpay/optimize-svg-components'
export const SVG_OPTIMIZE_COMPLETED_COMMENT = `/* ${SVG_OPTIMIZED_COMMENT_CONTENT} */`
export const PROPS_IDENTIFIER_NAME = 'props'
export const FIRST_RANGE = [0, 0]
