# Adjust according to your needs
name: Release Canary

on:
    issue_comment:
        types:
            - created

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    canary:
        if: ${{ github.event.issue.pull_request && (github.event.comment.body == 'canary-publish' || github.event.comment.body == '/canary-publish')}}
        runs-on: ubuntu-latest
        steps:
            - name: Get PR branch name
              id: get_branch
              run: |
                  PR=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" ${{ github.event.issue.pull_request.url }})
                  echo "::set-output name=branch::$(echo $PR | jq -r '.head.ref')"

            - uses: actions/checkout@v4
              with:
                  ref: ${{ steps.get_branch.outputs.branch }}
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '22'
                  cache: 'pnpm'

            - name: Install Dependencies
              run: pnpm install --frozen-lockfile

            - name: Build
              run: pnpm build

            - name: Canary Publish
              uses: NaverPayDev/changeset-actions/canary-publish@main
              with:
                  github_token: ${{ secrets.ACTION_TOKEN }} # Add user PAT if necessary
                  npm_tag: canary # Specify the npm tag to use for deployment
                  npm_token: ${{ secrets.NPM_TOKEN }} # Provide the token required for npm publishing
                  publish_script: pnpm run release:canary # Script to execute Canary deployment
                  packages_dir: packages # Directory of packages to detect changes (default: packages,share)
                  excludes: '.turbo,.github' # Files or directories to exclude from change detection
                  version_template: '{VERSION}-canary.{DATE}-{COMMITID7}'
